import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "background": "#faf9ff",
        "surface": "#faf9ff",
        "surface-bright": "#faf9ff",
        "surface-alt": "#FBFAFE",
        "surface-dim": "#dad9df",
        "surface-variant": "#e3e2e8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f9",
        "surface-container": "#eeedf3",
        "surface-container-high": "#e8e7ed",
        "surface-container-highest": "#e3e2e8",
        "surface-tint": "#5c35f3",
        "on-background": "#1a1b20",
        "on-surface": "#1a1b20",
        "on-surface-variant": "#484556",
        "inverse-surface": "#2f3035",
        "inverse-on-surface": "#f1f0f6",
        "primary": "#4200d8",
        "primary-container": "#5b34f2",
        "primary-fixed": "#e5deff",
        "primary-fixed-dim": "#c8bfff",
        "on-primary": "#ffffff",
        "on-primary-container": "#dad2ff",
        "on-primary-fixed": "#1a0064",
        "on-primary-fixed-variant": "#4300da",
        "inverse-primary": "#c8bfff",
        "secondary": "#605a7a",
        "secondary-container": "#e0d8fe",
        "secondary-fixed": "#e6deff",
        "secondary-fixed-dim": "#c9c2e7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#625d7d",
        "on-secondary-fixed": "#1c1734",
        "on-secondary-fixed-variant": "#484362",
        "tertiary": "#4813cb",
        "tertiary-container": "#603be2",
        "tertiary-fixed": "#e6deff",
        "tertiary-fixed-dim": "#cabeff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#dbd2ff",
        "on-tertiary-fixed": "#1c0062",
        "on-tertiary-fixed-variant": "#4914cb",
        "error": "#F04438",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#787588",
        "outline-variant": "#c9c4d9",
        "border-subtle": "#E2E0EF",
        "success": "#12B76A",
        "text-muted": "#56516E",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-caps": ["IBM Plex Sans", "sans-serif"],
        "code-data": ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-data": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}

export default config
